### ISSUE TITLE
Editor File invalid

### ISSUE THREAD

**Issue by JavierRefuerzo** [simplextech/pg3_docs#2]
HI @simplextech ,

Please see the following UD Mobile issue.  It appears the Editor file has invalid XML formatting

https://github.com/UniversalDevicesInc/UD-Mobile-iOS/issues/51

**Comment by simplextech** [comment]
Javi - 

Can you provide more details around the editors.xml error?  The editors.xml file exists but has no entries as none are needed.  Here's the file contents.

`<editors>
</editors>
`
Is this no longer valid with ISY and UD Mobile?

**Comment by JavierRefuerzo** [comment]
Checking with OP now, the response I received stripped XML so I did not see the empty editor values.

**Comment by JavierRefuerzo** [comment]
Thanks for looking,  XML is valid.
